include classpath("application.conf")

queues {
  document-ingestion {
    defaultVisibilityTimeout = 30 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "document-ingestion-dlq"
      maxReceiveCount = 3
    }
  }
  document-ingestion-dlq { }
}
